### PR TITLE
How to specify software

### PR DESCRIPTION
**Pull request by etabas**
@MBenkert16  @lindsaysd @afpearlman @jae9970 @Divgo123 can you please provide me with some feedback?

### CODE REVIEW

**Comment by lindsaysd** [comment]
Hey Emily, could you also add a picture to make it a little more visual? Otherwise, nice succinct write up!

**Comment by etabas** [comment]
@lindsaysd @afpearlman @Divgo123 @jae9970 @MBenkert16 I've made the updates you've requested. Is this :+1: to :ship: ?

**Comment by lindsaysd** [comment]
Emily, looks ready to ship to me!

**Comment by MBenkert16** [comment]
Looks good to :ship: to me as well!

**Comment by etabas** [comment]
@MBenkert16 @lindsaysd thanks!

**Pull request merged**
