### PR TITLE
File formats

### PR DESCRIPTION
**Pull request by jae9970**
@etabas @afpearlman @lindsaysd @Divgo123 @MBenkert16 

:hand: Please feel free make comments on my file. Specifically, I would love to make my file look as beautiful as Alex's HTML-style :cool: file.

### CODE REVIEW

**Comment by lindsaysd** [comment]
Good stuff Ryan! Could you add a summary sentence at the beginning or end about why we non-technical people might care about file formats, or why the new file formats have benefitted us?

**Comment by lindsaysd** [comment]
Ryan, this is looking pretty good - looks ready to ship to me.

**Comment by MBenkert16** [comment]
Seconding Lindsay - looks ready to :ship: to me!

**Comment by etabas** [comment]
Looks :+1: to :ship: !

**Pull request merged**
